name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Build Frontend
        run: |
          cd client
          npm run build
        env:
          VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.FRONTEND_VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.FRONTEND_VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.FRONTEND_VERCEL_ORG_ID }}
        run: |
          npm install -g vercel
          cd client
          vercel --prod --token $VERCEL_TOKEN --confirm
